on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install ADF Utilities
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Validate ADF Code
        run: npm run build validate ${{ github.workspace }}/ /subscriptions/d3f41627-fc6d-4d2f-b851-5f06fc474027/resourceGroups/covid-reporting-rg/providers/Microsoft.DataFactory/factories/covid-reporting-adf-name1
        working-directory: ${{ github.workspace }}/build

      - name: Export ARM Template
        run: npm run build export ${{ github.workspace }}/ /subscriptions/d3f41627-fc6d-4d2f-b851-5f06fc474027/resourceGroups/covid-reporting-rg/providers/Microsoft.DataFactory/factories/covid-reporting-adf-name1 ExportedArmTemplate
        working-directory: ${{ github.workspace }}/build

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/build/ExportedArmTemplate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ExportedArmTemplate

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy ADF via ARM Template
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: test-cicd-rg
          dataFactoryName: test-cicd-adf1
          armTemplateFile: ExportedArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: ExportedArmTemplate/ARMTemplateParametersForFactory.json
          skipAzModuleInstallation: true
